packages:
  - packages/*

catalog:
  '@ckeditor/ckeditor5-dev-build-tools': ^53.2.0
  '@ckeditor/ckeditor5-dev-bump-year': ^53.2.0
  '@ckeditor/ckeditor5-dev-changelog': ^53.2.0
  '@ckeditor/ckeditor5-dev-ci': ^53.2.0
  '@ckeditor/ckeditor5-dev-dependency-checker': ^53.2.0
  '@ckeditor/ckeditor5-dev-docs': ^53.2.0
  '@ckeditor/ckeditor5-dev-release-tools': ^53.2.0
  '@ckeditor/ckeditor5-dev-stale-bot': ^53.2.0
  '@ckeditor/ckeditor5-dev-tests': ^53.2.0
  '@ckeditor/ckeditor5-dev-translations': ^53.2.0
  '@ckeditor/ckeditor5-dev-utils': ^53.2.0
  '@ckeditor/ckeditor5-dev-web-crawler': ^53.2.0
  '@ckeditor/ckeditor5-inspector': ^5.0.0
  es-toolkit: 1.39.5
  sanitize-html: ^2.13.0
  typescript: 5.3.3
  webpack: ^5.101.3
  webpack-cli: ^6.0.1

dangerouslyAllowAllBuilds: true

ignoreWorkspaceCycles: true

linkWorkspacePackages: true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

preferFrozenLockfile: true

shamefullyHoist: true

shellEmulator: true
