packages:
  - packages/*

allowBuilds:
  '@ckeditor/ckeditor5-dev-tests': true
  '@ckeditor/ckeditor5-mermaid@https://codeload.github.com/ckeditor/ckeditor5-mermaid/tar.gz/68116cca61fcc93c0026bd5499c9fd5e39391e03': true
  '@parcel/watcher': true
  '@swc/core': true
  'core-js': true
  'esbuild': true
  'hexo-util': true
  'puppeteer': true
  'sharp': true
  'snyk': true

# This section must be synchronized with `ckeditor/ckeditor5-commercial`.
overrides:
  '@iktakahiro/markdown-it-katex>katex': ^0.16.0
  'diff@^7': '^8.0.3'
  'fast-xml-parser@^5': '^5.3.8'
  'http-proxy-agent@^5': '^6.1.1'
  'lodash@^4': '^4.18.0'
  'markdown-it-toc': 'npm:@maboloshi/markdown-it-toc@1.1.1'
  'minimatch@^9': '^9.0.7'
  'path-to-regexp@^0': '^0.1.13'
  'qs@^6': '^6.15.2'
  'serialize-javascript@^6': '^7.0.5'
  'uuid@^8': '^14.0.0'
  'uuid@^9': '^14.0.0'
  'uuid@^11': '^14.0.0'
  'yauzl@^2': '^3.2.1'
  'ws@^8': '^8.20.1'
  'js-cookie@^3': '^3.0.8'
  'tmp@^0.2': '^0.2.7'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'umberto'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
ignoreWorkspaceCycles: true
verifyDepsBeforeRun: false
