packages:
  - packages/*

onlyBuiltDependencies:
  - '@ckeditor/ckeditor5-dev-tests'
  - '@ckeditor/ckeditor5-mermaid'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - hexo-util
  - puppeteer
  - sharp

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'umberto'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
ignoreWorkspaceCycles: true
