packages:
  - packages/*

onlyBuiltDependencies:
  - '@ckeditor/ckeditor5-dev-tests'
  - '@ckeditor/ckeditor5-mermaid'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - hexo-util
  - puppeteer
  - sharp
  - snyk

# This section must be synchronized with `ckeditor/ckeditor5-commercial`.
overrides:
  'markdown-it-toc': 'npm:@maboloshi/markdown-it-toc@1.1.1'
  '@iktakahiro/markdown-it-katex>katex': '^0.16.0'
  '@ckeditor/jsdoc-plugins>jsdoc': '-'
  '@tootallnate/once@^2': '^3.0.1'
  'diff@^7': '^8.0.3'
  'lodash@^4': '^4.18.1'
  'lodash-es@^4': '^4.18.1'
  'minimatch@^9': '^9.0.7'
  'qs@^6': '^6.14.2'
  'serialize-javascript@^6': '^7.0.5'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'umberto'
  - 'follow-redirects' # Remove after 2026-04-16.

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
ignoreWorkspaceCycles: true
