packages:
  - packages/*

onlyBuiltDependencies:
  - '@ckeditor/ckeditor5-dev-tests'
  - '@ckeditor/ckeditor5-mermaid'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - hexo-util
  - puppeteer
  - sharp

# This section must be synchronized with `ckeditor/ckeditor5-commercial`.
overrides:
  markdown-it@^13.0.0: '^14.1.1'
  markdown-it-toc: 'npm:@maboloshi/markdown-it-toc@1.1.1'
  '@iktakahiro/markdown-it-katex>katex': ^0.16.0
  '@ckeditor/jsdoc-plugins>jsdoc': '-'
  'qs@^6.0.0': '^6.14.2'
  'diff@<8': '^8.0.3'
  'lodash-es': '^4.17.23'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'umberto'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
ignoreWorkspaceCycles: true
