packages:
  - packages/*

ignoreWorkspaceCycles: true

linkWorkspacePackages: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - umberto

onlyBuiltDependencies:
  - '@ckeditor/ckeditor5-dev-tests'
  - '@ckeditor/ckeditor5-dev-web-crawler'
  - '@ckeditor/ckeditor5-mermaid'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - hexo-util
  - puppeteer
  - sharp

overrides:
  '@ckeditor/jsdoc-plugins>jsdoc': '-'
  '@iktakahiro/markdown-it-katex>katex': ^0.16.0
  diff@<8: ^8.0.3
  markdown-it-toc: npm:@maboloshi/markdown-it-toc@1.1.1
  qs@^6.0.0: ^6.14.1

preferFrozenLockfile: true

shamefullyHoist: true

shellEmulator: true
