/**
 * @license Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import Collection from '../../utils/collection.js';

/**
 * Mixin that injects the common Toolbar–like bindings.
 *
 * See {@link ui.bindings.Toolbar}.
 *
 * @mixin ui.bindings.ToolbarBindingsMixin
 */
const ToolbarBindingsMixin = {
	/**
	 * Adds items like buttons to the toolbar. Buttons are generated by the
	 * {@link ui.editorUI.EditorUI#featureComponents} factory.
	 */
	bindToolbarItems() {
		/**
		 * Collection of toolbar items.
		 *
		 * @member {utils.Collection} ui.bindings.ToolbarBindingsMixin#items
		 */
		this.items = new Collection();

		if ( this.model.config ) {
			// Translate config to dynamic item collection.
			for ( let name of this.model.config ) {
				this.items.add( { name } );
			}
		}

		this.collections.get( 'items' ).bind( this.items ).as( ( { name } ) => {
			return this.editor.ui.featureComponents.create( name );
		} );
	}
};

export default ToolbarBindingsMixin;
