/**
 * @license Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

import GoogleDocsNormalizer from '../../src/normalizers/genericnormalizer';

// `execute()` of the generic normalizer is tested with autogenerated normalization tests.
describe( 'GoogleDocsNormalizer', () => {
	const normalizer = new GoogleDocsNormalizer();

	describe( 'isActive()', () => {
		it( 'should return always true ', () => {
			expect( normalizer.isActive() ).to.be.true;
		} );
	} );
} );
