#!/bin/bash

# @license Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
# For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license

BRANCH_CHANGED=$3

node scripts/post-checkout.js $BRANCH_CHANGED $PWD
